# Generated by Django 5.1.3 on 2024-11-17 17:02

import tmdb_database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SortItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('poster_path', models.ImageField(blank=True, upload_to=tmdb_database.models.get_media_path)),
                ('backdrop_path', models.ImageField(blank=True, upload_to=tmdb_database.models.get_media_path)),
                ('vote_average', models.FloatField(blank=True, default=0)),
                ('popularity', models.FloatField(blank=True, default=0)),
                ('overview', models.TextField(blank=True, max_length=2000)),
                ('language', models.CharField(blank=True, max_length=200)),
                ('genres', models.ManyToManyField(to='tmdb_database.genre')),
            ],
        ),
    ]
