# Generated by Django 5.1.3 on 2024-11-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb_database', '0002_sortitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('poster_path', models.ImageField(upload_to='')),
                ('backdrop_path', models.ImageField(upload_to='')),
                ('vote_average', models.FloatField()),
                ('popularity', models.FloatField()),
                ('overview', models.TextField(max_length=2000)),
                ('language', models.CharField(max_length=200)),
                ('genres', models.ManyToManyField(to='tmdb_database.genre')),
            ],
        ),
    ]
