# Generated by Django 5.1.3 on 2024-11-17 15:27

import tmdb_database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb_database', '0005_alter_movie_popularity_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.ImageField(blank=True, upload_to=tmdb_database.models.get_media_path),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.ImageField(blank=True, upload_to=tmdb_database.models.get_media_path),
        ),
    ]
